#!/bin/sh
set -e

# Get environment variables or use defaults
BACKEND_PORT=${BACKEND_PORT:-5002}
BACKEND_HOST=${BACKEND_HOST:-api}

echo "Configuring nginx to connect to backend at ${BACKEND_HOST}:${BACKEND_PORT}"

# Generate nginx config with exact backend address
cat > /etc/nginx/conf.d/default.conf << EOF
# Autogenerated nginx configuration
# Connecting to backend at ${BACKEND_HOST}:${BACKEND_PORT}

# Define hardcoded upstream using explicit port
upstream backend_api {
    server ${BACKEND_HOST}:${BACKEND_PORT};
}

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip compression
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;
    gzip_types
      application/javascript
      application/json
      application/x-javascript
      text/css
      text/javascript
      text/plain
      text/xml;
    
    # API proxy - explicit backend config
    location /api/ {
        # Use explicit upstream with hardcoded port
        proxy_pass http://backend_api/api/;
        
        # Error handling
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_intercept_errors on;
        
        # Headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        
        # Long timeouts for video processing
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
        proxy_buffers 8 16k;
        proxy_buffer_size 32k;
        
        # Upload size limit
        client_max_body_size 100M;
    }

    # Static files
    location / {
        try_files \$uri \$uri/ /index.html;
        expires 1d;
        add_header Cache-Control "public, max-age=86400";
    }

    # Health check
    location /health {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
EOF

echo "Starting nginx"
exec nginx -g 'daemon off;'